
= Introduction

SM4 <<GBT.32907-2016>> <<ISO.IEC.18033-3.AMD2>> is a cryptographic standard
issued by the Organization of State Commercial Administration of China <<OSCCA>>
as an authorized cryptographic algorithm for the use within China.
The algorithm is published in public.

SM4 is a symmetric encryption algorithm, specifically a blockcipher,
designed for data encryption.

== Purpose

This document does not aim to introduce a new algorithm, but to
provide a clear and open description of the SM4 algorithm in English,
and also to serve as a stable reference for IETF documents that utilize
this algorithm.

While this document is similar to <<SM4-En>> in nature, <<SM4-En>> is a textual
translation of the "SMS4" algorithm <<SM4>> published in 2006, while this
document follows the updated description and structure of <<GBT.32907-2016>>
published in 2016. Sections 1 to 7 of this document directly map to the
corresponding sections numbers of the <<GBT.32907-2016>> standard for
convenience of the reader.

This document also provides additional information on the design
considerations of the algorithm <<SM4-Details>>, practical usage and
implementation of SM4 specifying modes of operations that are known
to be used with SM4 (see <<sm4-modes>>), and providing the
SM4 OIDs (see <<sm4-oids>>).


== History

The "SMS4" algorithm (the former name of SM4) was invented by
Shu-Wang Lu <<LSW-Bio>>, first published in 2003 as part of
<<GB.15629.11-2003>>, then published independently in 2006 <<SM4>> by the OSCCA,
officially renamed to "SM4" in 2012 in <<GMT-0002-2012>> published by the OSCCA,
and finally standardized in 2016 as a Chinese National Standard (GB Standard)
<<GBT.32907-2016>>. SM4 is also standardized in <<ISO.IEC.18033-3.AMD2>>
by the International Organization for Standardization in 2017.

SMS4 was originally created for use in protecting wireless networks <<SM4>>,
and is mandated in the Chinese National Standard for Wireless LAN WAPI (Wired
Authentication and Privacy Infrastructure) <<GB.15629.11-2003>>. A proposal
was made to adopt SMS4 into the IEEE 802.11i standard, but the algorithm
was eventually not included due to concerns of introducing inoperability
with existing ciphers.

The latest SM4 standard <<GBT.32907-2016>> was proposed by the OSCCA,
standardized through TC 260 of the Standardization Administration of the
People's Republic of China (SAC), and was drafted by the following
individuals at the Data Assurance and Communication Security Research
Center (DAS Center) of the Chinese Academy of Sciences, the China
Commercial Cryptography Testing Center and the Beijing Academy of
Information Science & Technology (BAIST):

* Shu-Wang Lu
* Dai-Wai Li
* Kai-Yong Deng
* Chao Zhang
* Peng Luo
* Zhong Zhang
* Fang Dong
* Ying-Ying Mao
* Zhen-Hua Liu

