= Functions

== Round Function $$F$$

The round function $$F$$ is defined as:

$$
F(X_0, X_1, X_2, X_3, rk) = X_0 xor T(X_1 xor X_2 xor X_3 xor rk)
$$

Where:

* Each $$X_i$ is 32-bit wide.
* The round key $$rk$$ is 32-bit wide.

== Permutations $$T$$ and $$T'$$

$$T$$ is a reversible permutation that outputs 32 bits from a 32-bit input.

It consists of a nonlinear transform $$tau$$ and linear transform $$L$$.

$$
T(.) = L(tau(.))
$$


The permutation $$T'$$ is created from $$T$$ by replacing the
linear transform function $$L$$ with $$L'$$.

$$
T'(.) = L'(tau(.))
$$


=== Nonlinear Transformation tau

$$tau$$ is composed of four parallel S-boxes.

Given a 32-bit input $$A$$, where each $$a_i$$ is a 8-bit string:

$$
A = (a_0, a_1, a_2, a_3)
$$

The output is a 32-bit $$B$$, where each $$b_i$$ is a 8-bit string:

$$
B = (b_0, b_1, b_2, b_3)
$$

$$B$$ is calculated as follows:

$$
(b_0, b_1, b_2, b_3) = tau(A)
$$

$$
tau(A) = (S(a_0), S(a_1), S(a_2), S(a_3))
$$


=== Linear Transformations $$L$$ and $$L'$$

The output of nonlinear transformation function $$tau$$ is used as input
to linear transformation function $$L$$.

Given $$B$$, a 32-bit input.

The linear transformation $$L'$$ is defined as follows.

$$
L(B) = B xor (B <<< 2) xor (B <<< 10) xor (B <<< 18) xor (B <<< 24)
$$


The linear transformation $$L'$$ is defined as follows.

$$
L'(B) = B xor (B <<< 13) xor (B <<< 23)
$$

=== S-box $$S$$

The S-box $$S$$ used in nonlinear transformation $$tau$$ is given in
the lookup table shown in <<diagram-sm4-sbox>> with hexadecimal values.

// TODO: asciidoctor-rfc takes a long time to process this table.

////
[#table-sm4-sbox]
.SM4 S-box Values
[grid=none,align=center]
|===
h|   | 0  | 1  | 2  | 3  | 4  | 5  | 6  | 7  | 8  | 9  | A  | B  | C  | D  | E  | F

h| 0 | D6 | 90 | E9 | FE | CC | E1 | 3D | B7 | 16 | B6 | 14 | C2 | 28 | FB | 2C | 05
h| 1 | 2B | 67 | 9A | 76 | 2A | BE | 04 | C3 | AA | 44 | 13 | 26 | 49 | 86 | 06 | 99
h| 2 | 9C | 42 | 50 | F4 | 91 | EF | 98 | 7A | 33 | 54 | 0B | 43 | ED | CF | AC | 62
h| 3 | E4 | B3 | 1C | A9 | C9 | 08 | E8 | 95 | 80 | DF | 94 | FA | 75 | 8F | 3F | A6
h| 4 | 47 | 07 | A7 | FC | F3 | 73 | 17 | BA | 83 | 59 | 3C | 19 | E6 | 85 | 4F | A8
h| 5 | 68 | 6B | 81 | B2 | 71 | 64 | DA | 8B | F8 | EB | 0F | 4B | 70 | 56 | 9D | 35
h| 6 | 1E | 24 | 0E | 5E | 63 | 58 | D1 | A2 | 25 | 22 | 7C | 3B | 01 | 21 | 78 | 87
h| 7 | D4 | 00 | 46 | 57 | 9F | D3 | 27 | 52 | 4C | 36 | 02 | E7 | A0 | C4 | C8 | 9E
h| 8 | EA | BF | 8A | D2 | 40 | C7 | 38 | B5 | A3 | F7 | F2 | CE | F9 | 61 | 15 | A1
h| 9 | E0 | AE | 5D | A4 | 9B | 34 | 1A | 55 | AD | 93 | 32 | 30 | F5 | 8C | B1 | E3
h| A | 1D | F6 | E2 | 2E | 82 | 66 | CA | 60 | C0 | 29 | 23 | AB | 0D | 53 | 4E | 6F
h| B | D5 | DB | 37 | 45 | DE | FD | 8E | 2F | 03 | FF | 6A | 72 | 6D | 6C | 5B | 51
h| C | 8D | 1B | AF | 92 | BB | DD | BC | 7F | 11 | D9 | 5C | 41 | 1F | 10 | 5A | D8
h| D | 0A | C1 | 31 | 88 | A5 | CD | 7B | BD | 2D | 74 | D0 | 12 | B8 | E5 | B4 | B0
h| E | 89 | 69 | 97 | 4A | 0C | 96 | 77 | 7E | 65 | B9 | F1 | 09 | C5 | 6E | C6 | 84
h| F | 18 | F0 | 7D | EC | 3A | DC | 4D | 20 | 79 | EE | 5F | 3E | D7 | CB | 39 | 48
|===
////


[[diagram-sm4-sbox]]
.SM4 S-box Values
[align=center]
====
[align=center]
....
   |  0  1  2  3  4  5  6  7  8  9  A  B  C  D  E  F
---|-------------------------------------------------
 0 | D6 90 E9 FE CC E1 3D B7 16 B6 14 C2 28 FB 2C 05
 1 | 2B 67 9A 76 2A BE 04 C3 AA 44 13 26 49 86 06 99
 2 | 9C 42 50 F4 91 EF 98 7A 33 54 0B 43 ED CF AC 62
 3 | E4 B3 1C A9 C9 08 E8 95 80 DF 94 FA 75 8F 3F A6
 4 | 47 07 A7 FC F3 73 17 BA 83 59 3C 19 E6 85 4F A8
 5 | 68 6B 81 B2 71 64 DA 8B F8 EB 0F 4B 70 56 9D 35
 6 | 1E 24 0E 5E 63 58 D1 A2 25 22 7C 3B 01 21 78 87
 7 | D4 00 46 57 9F D3 27 52 4C 36 02 E7 A0 C4 C8 9E
 8 | EA BF 8A D2 40 C7 38 B5 A3 F7 F2 CE F9 61 15 A1
 9 | E0 AE 5D A4 9B 34 1A 55 AD 93 32 30 F5 8C B1 E3
 A | 1D F6 E2 2E 82 66 CA 60 C0 29 23 AB 0D 53 4E 6F
 B | D5 DB 37 45 DE FD 8E 2F 03 FF 6A 72 6D 6C 5B 51
 C | 8D 1B AF 92 BB DD BC 7F 11 D9 5C 41 1F 10 5A D8
 D | 0A C1 31 88 A5 CD 7B BD 2D 74 D0 12 B8 E5 B4 B0
 E | 89 69 97 4A 0C 96 77 7E 65 B9 F1 09 C5 6E C6 84
 F | 18 F0 7D EC 3A DC 4D 20 79 EE 5F 3E D7 CB 39 48
....
====

For example, input "EF" will produce an output read from the S-box table
row E and column F, giving the result $$S(EF) = 84$$.

