= Algorithm


[#sm4-encryption]
== Encryption

The encryption algorithm consists of 32 rounds and 1 reverse transform $$R$$.

Given a 128-bit plaintext input, where each $$X_i$$ is 32-bit wide:

----
(X_0, X_1, X_2, X_3)
----

The output is a 128-bit ciphertext, where each $$Y_i$$ is 32-bit wide:

----
(Y_0, Y_1, Y_2, Y_3)
----

Each round key is designated as $$rk_i$$, where each $$rk_i$$ is 32-bit wide
and $$i = 0, 1, 2, ..., 31$$.

a. 32 rounds of calculation
+
----
i = 0, 1, ..., 31

X_{i+4} = F(X_i, X_{i+1}, X_{i+2}, X_{i+3}, rk_i)
----

b. reverse transformation
+
----
(Y_0, Y_1, Y_2, Y_3) = R(X_32, X_33, X_34, X_35)

R(X_32, X_33, X_34, X_35) = (X_35, X_34, X_33, X_32)
----

Please refer to <<appendix-a>> for sample calculations.

A flow of the calculation is given in <<diagram-sm4-flow>>.

[[diagram-sm4-flow]]
.SM4 Encryption Flow
====
[align=center]
....

                   128-bits plaintext
              \___________________________/
                            |
                            v
               X_0     X_1     X_2     X_3
                |       |       |       |
                v       v       v       v
              +---------------------------+
  Round 1     |      Round Function       | <--rk_0
              +---------------------------+
                |       |       |       |
               X_1     X_2     X_3     X_4
                |       |       |       |
                v       v       v       v
              +---------------------------+
  Round 2     |      Round Function       | <--rk_1
              +---------------------------+
                |       |       |       |
               X_2     X_3     X_4     X_5
                |       |       |       |
                v       v       v       v
                           ...

               X_31    X_32    X_33    X_34
                |       |       |       |
                v       v       v       v
              +---------------------------+
  Round 32    |      Round Function       | <--rk_31
              +---------------------------+
                |       |       |       |
               X_32    X_33    X_34    X_35
                |       |       |       |
                v       v       v       v
              +---------------------------+
              | Reverse Transformation R  |
              +---------------------------+
                |       |       |       |
               Y_0     Y_1     Y_2     Y_3

              \___________________________/
                            |
                            v
                   128-bits ciphertext

....
====


[#sm4-decryption]
== Decryption

Decryption takes an identical process as encryption, with the only difference
the order of the round key sequence.

During decryption, the round key sequence is:

----
(rk_31, rk_30, ..., rk_0)
----

== Key Schedule

Round keys used during encryption are derived from the encryption key.

Specifically, given the encryption key $$MK$$, where each $$MK_i$$ is 32-bit
wide:

----
MK = (MK_0, MK_1, MK_2, MK_3)
----

Each round key $$rk_i$$ is created as follows, where $$i = 0, 1, ..., 31$$.

----
(K_0, K_1, K_2, K_3) =
    (MK_0 xor FK_0, MK_1 xor FK_1, MK_2 xor FK_2, MK_3 xor FK_3)

rk_i = K_{i + 4}

K_{i + 4} =
    K_i xor T' (K_{i + 1} xor K_{i + 2} xor K_{i + 3} xor CK_i)
----

Since the decryption key is identical to the encryption key, the round keys
used in the decryption process are derived from the decryption key through
the identical process to that of during encryption.

<<diagram-round-function>> depicts the i-th round of SM4.

.SM4 Round Function For the i-th Round
[#diagram-round-function]
====

[align=center]
....

  X_i               rk_i  X_{i+1} X_{i+2} X_{i+3}
   |                 |      |       |       |
   |                 |      |       |       |
   |                 v      |       |       |
 +---+    +---+    +---+    |       |       |
 | X |    |   |    | X | <--+       |       |
 | O | <- | T | <- | O | <----------+       |
 | R |    |   |    | R | <------------------+
 +---+    +---+    +---+    |       |       |
   |                       /       /       /
   |                      /       /       /
   |                     /       /       /
    \--------------------------------------=
                       /       /       /    \
                      /       /       /     |
     /---------------/       /       /      |
    |                       |       |       |
 X_{i+1}                 X_{i+2} X_{i+3} X_{i+4}

....
====


=== Family Key $$FK$$

Family key $$FK$$ given in hexadecimal notation, is:

[source,align=center]
----
FK_0 = A3B1BAC6
FK_1 = 56AA3350
FK_2 = 677D9197
FK_3 = B27022DC
----

=== Constant Key $$CK$$

The method to retrieve values from the constant key $$CK$$ is as follows.

Let $$ck_{i, j}$$ be the $$j$$-th byte ($$i = 0, 1, ..., 31; j = 0, 1, 2, 3$$) of $$CK_i$$.

Therefore, each $$ck_{i, j}$$ is a 8-bit string, and each $$CK_i$$ a 32-bit word.

----
CK_i = (ck_{i, 0}, ck_{i, 1}, ck_{i, 2}, ck_{i, 3})
----

----
ck_{i, j} = (4i + j) x 7 (mod 256)
----

The values of the constant key $$CK_i$$, where $$(i = 0, 1, ..., 31)$$, in
hexadecimal, are:

[source,align=center]
----
CK_0  = 00070E15   CK_16 = C0C7CED5
CK_1  = 1C232A31   CK_17 = DCE3EAF1
CK_2  = 383F464D   CK_18 = F8FF060D
CK_3  = 545B6269   CK_19 = 141B2229
CK_4  = 70777E85   CK_20 = 30373E45
CK_5  = 8C939AA1   CK_21 = 4C535A61
CK_6  = A8AFB6BD   CK_22 = 686F767D
CK_7  = C4CBD2D9   CK_23 = 848B9299
CK_8  = E0E7EEF5   CK_24 = A0A7AEB5
CK_9  = FC030A11   CK_25 = BCC3CAD1
CK_10 = 181F262D   CK_26 = D8DFE6ED
CK_11 = 343B4249   CK_27 = F4FB0209
CK_12 = 50575E65   CK_28 = 10171E25
CK_13 = 6C737A81   CK_29 = 2C333A41
CK_14 = 888F969D   CK_30 = 484F565D
CK_15 = A4ABB2B9   CK_31 = 646B7279
----

