
[#cryptanalysis]
= Cryptanalysis Results
//3 SM4算法安全性分析

////
丄1 SM4算法安全性分析现状

SM4分组密码算法自从2006年1月发布以来，国内外众多的科研人员对其安全性进行了评估，评估方法几乎涵盖了目前已知的所有分组密码分析方法，如差分密码分析、线性密码分析、不可能差分分析等等.公开的评估结果表明，SM4分组密码算法能够抵抗目前已知的所有攻击，拥有足够的安全冗余度.
////

SM4 has been heavily cryptanalyzed by international researchers since
it was first published in January 2016. Nearly all currently known
cryptanalysis techniques have already been applied to SM4,
but there have been no known feasible attacks against the full SM4
blockcipher and results demonstrate that SM4 currently provides a
suitable security margin, by the time of publishing this document.

A summary of cryptanalysis results are presented in the following
sections.

A number of attacks have been attempted on SM4, such as <<SM4-LDA>>
<<SM4-Linear>>.

There are, however, security concerns with regards to side-channel attacks
<<SideChannel>> when the SM4 algorithm is implemented in a hardware device
<<SM4-Power>>.

For instance, <<SM4-Power>> illustrated an attack by measuring the power
consumption of the device. A chosen ciphertext attack, assuming a fixed
correlation between the round keys and data mask, is able to recover the round
key successfully. When the SM4 algorithm is implemented in hardware, the
parameters and keys **SHOULD** be randomly generated without fixed correlation.

There have been improvements to the hardware embodiment design for SM4, such
as <<SM4-VLSI>>, that may resist such attacks.

In order to improve security of the SM4 cryptographic process, secure white-box
implementations such as <<SM4-WhiteBox>> have been proposed. Speed enhancements,
such as <<SM4-HiSpeed>>, have also been proposed.


////
1) 差分密码分析

张蕾等人<<SM4-DiffZhang1>.首先给出了 SM4的21轮差分分 析，数据复杂度为2118个选择明文，时间复杂度为 2126 8次算法加密.接着，张文涛等人<<SM4-DiffZhang2>>给出了 SM4 算法18轮差分特征，能够攻击到22轮，数据复杂 度为2117个选择明文，时间复杂度为2^3次算法 加密.张美玲等人[14]也利用一些18轮的差分特征 分析了 22轮SM4算法，数据复杂度为2117个选择 明文，时间复杂度为2123次算法加密，存储复杂度 为2112. 2011年，苏波展等人％找到了 19轮的有效 差分特征，将SM4的差分分析推进了 1轮，达到23 轮，攻击需要的数据复杂度为2118个选择明文，时 间复杂度为212〃次加密，存储复杂度为212()-7.
////

== Differential Cryptanalysis

<<SM4-DiffZhang1>> gave a 21-round differential analysis with data complexity
$$2^188$$, time complexity $$2^126.8$$ encryptions.

<<SM4-DiffZhang2>> gave a 18-round differential characteristics with an attack
that reaches the 22nd round, with data complexity $$2^117$$ and time complexity
$$2^112.3$$.

<<SM4-DiffZhang3>> utilized 18-round differential characteristics for the 22nd
round with $$2^117$$ chosen plaintexts with time complexity $$2^123$$
encryptions, storage complexity of $$2^112$$.

<<SM4-DiffSu>> In 2011, Su Bozan gave a 19 round differential characteristics
and pushed their attack to the 23rd round, with data complexity of $$2^118$$
chosen plaintexts, time complexity $$2^126.7$$ encryptions, and storage
complexity $$2^120.7$$.


== Linear Cryptanalysis

<<SM4-LinearEtrog>> 2008 Etrog et al. presented a linear analysis result for 22
rounds of SM4, the data complexity is given as $$2^188.4$$ known plaintexts,
time complexity $$2^117$$ encrypt operations.

<<SM4-LinearDong>> 2011 Dong presented a linear analysis result for 20 rounds,
$$2^110.4$$ known ciphertexts, $$2^106.8$$ encryption operations, storage
complexity $$2^90$$.

<<SM4-LinearLiu>> 2014 Liu et al. presented a result for 23-rounds of SM4
linear analysis, time complexity $$2^112$$ encryption operations, data
complexity $$2^126.54$$ known ciphertexts, storage complexity $$2^116$$.

<<SM4-NLC>> in 2017 Liu et  al. presented a result for 24-rounds of linear
cryptanalysis for SM4, with time complexity of $$2^122.6$$ encryptions,
data complexity of $$2^122.6$$ known ciphertexts, and
storage complexity of $$2^85$$. As of the publishing of this document this
represents the highest number of rounds achieved.

////
2) 线性密码分析

2008年，Etrog等人[16]给出了 SM4的22轮 线性分析结果，分析方法的数据复杂度为2118 4个 已知明文，时间复杂度为2117次算法加密.2011 年，董晓丽[17]给出了 20轮SM4的线性分析结果，需要的数据复杂度为个已知明文，时间复杂 度为21。6’8次算法加密，存储量为29°. 2014年，Liu 等人[18]给出了 23轮SM4算法的线性分析结果， 时间复杂度为2122次算法加密，数据复杂度为 2126’54个已知明文，存储复杂度为2116.
////

== Multi-dimensional Linear Cryptanalysis

<<SM4-MLLiu>> In 2010, Liu et al. constructed a series of 18 rounds of linear
traces based on a 5-round circular linear trace, capable of attacking 22 rounds
of SM4. The required data complexity was $$2^112$$ known plaintexts, time
complexity $$2^124.21$$ encryption operations, with storage complexity of
$$2^118.83$$.

<<SM4-MLCho>> In 2010 Cho et al. gave a linear analysis of 23 rounds of SM4
with a data complexity of $$2^126.7$$ known plaintexts and a time complexity of
$$2^127$$, storage complexity of $$2^120.7$$.

<<SM4-MLLiu2>> In 2014, Liu et al. gave the results of multi-dimensional linear
analysis of 23 rounds of SM4 algorithm. The time complexity was $$2^122.7$$,
data complexity was $$2^122.6$$ known plaintext with storage complexity
$$2^120.6$$.

////
3) 多维线性密码分析

2010年，Liu等人[19]基于一条5轮的循环线 性迹，构造了多条18轮的线性迹，可以攻击到22 轮SM4，需要的数据复杂度为2112个已知明文，时 间复杂度为21%21次算法加密，存储量为2118«83.同 年，Cho等人％给出了 23轮SM4的线性分析，需 要的数据复杂度为212〃个已知明文，时间复杂度 为2127次算法加密，存储量为212a7. 20U年，Liu 等人[18]给出了 23轮SM4算法的多维线性分析结 果，时间复杂度为2122_7次算法加密，数据复杂度为 2122’6个已知明文，存储复杂度为2m6.
////

== Impossible Differential Cryptanalysis

<<SM4-IDCLu>> Lu et al. first presented 16 rounds of impossible differential
analysis of SM4 with the required data complexity $$2^105$$ chosen plaintexts,
time complexity $$2^107$$ encryption operations.

<<SM4-IDCToz>> Toz et al. revised the results of [21], that the data complexity
is actually $$2^117.05$$ chosen plaintexts, time complexity $$2^132.06$$ memory
queries, but since the complexity is already beyond the $$2^128$$ limit,
meaning that if 16-rounds SM4 encryption can be completed in 16 memory queries,
the attack results become invalid.

<<SM4-IDCWang>> In 2010 Wang et. al. pushed the impossible differential
cryptanalysis to 17 rounds of SM4, the data complexity is $$2^117$$ chosen
ciphertexts, time complexity $$2^132$$ memory queries.


////
4) 不可能差分密码分析

Lu等人首先给出了 SM4的16轮不可能 差分分析，需要的数据量为2W5个选择明文，时间 复杂度为21()7次加密.Toz等人[22]对文献[21]中的 结果进行了修正，攻击轮数不变，但是修正后的数 据复杂度为2117 °6个选择明文，时间复杂度达到了 W6内存查询.

注意到，该复杂度的值已经超越了 2128这个限值，如果16轮SM4的加密能够在16次 内存查询中完成，那么这个攻击结果就失效了. 2010年，Wang[23] SM4的不可能差分分析做到了 17轮，需要的数据复杂度为2117个选择明文，时 间复杂度为2132次内存查询.
////

== Zero-correlation Linear Cryptanalysis

<<SM4-ZCLC>> gives the results of multi-dimensional zero-correlation linear
cryptanalysis of a 14-round SM4 algorithm. The required data complexity is
$$2^123.5$$ known plaintexts, time complexity is $$2^120.7$$ encryption
operations and storage complexity of $$2^73$$ blocks.

////
5) 零相关线性分析

文献[24]给出了 14轮SM4算法的多维零相关线性分析结果，需要的数据复杂度为212&5个已 知明文，时间复杂度为212a7次算法加密，存储复杂 度为273个分组长度.
////

== Integral Cryptanalysis

<<SM4-ICLiu>> Liu et al. gave a 13-round integral analysis of SM4, which
required $$2^16$$ chosen plaintexts and time complexity of $$2^114$$ encryption
operations.

<<SM4-ICZhong>> Zhong et al. constructed a 12-round distinguisher of SM4 to
attack 14-round SM4, with data complexity of $$2^32$$ chosen plaintexts and
time complexity $$2^96.5$$ encryptions.

////
6) 积分密码分析

Liu等人[25]给出了SM4的13轮积分分析，需要的数据复杂度为216个选择明文，时间复杂度为
2114次加密.钟名富等人[26]构造了
12轮积分区分器，能够攻击M轮SM4算法，需要的数据复杂度
为232个选择明文，时间复杂度为296’5次算法加密•
////

== Algebraic Attack


Ji et al. <<SM4-AAJi>> and Erickson et al. <<SM4-AAEr>> utilized algebraic
methods such as XL, Groebner base and SAT to analyze the resistance of SM4
against algebraic attacks. The results demonstrate that SM4 is safe against
algebraic attacks, and specifically, has a higher resistance against algebraic
attacks than AES.

////
7) 代数攻击

ji等人[27]和Erickson等人_分别使用了XL方法、Groebner基方法以及SAT方法等不同的代
数方法对SM4抵抗代数攻击的能力进行了评估，
结果表明SM4在代数攻击下是安全的.特别地， 在XL方法下，SM4抗代数攻击的能力比AES还
要好•
////

== Matrix Attack

<<SM4-MatrixLu>> Lu et al. provided a matrix attack against 14-round SM4, with
data complexity $$2^121.82$$ chosen plaintexts, time complexity $$2^116.66$$
encryptions.

<<SM4-MatrixToz>> In 2008 Toz et al. lowered both data and time complexity of
the aformentioned attack to $$2^106.89$$ chosen ciphertexts and time complexity
of $$2^107.89$$.

In 2008, Zhang et al. <<SM4-MatrixZhang>> provided a matrix
attack against 16-round SM4, which required a data complexity of $$2^125$$
chosen plaintexts and time complexity of $$2^116$$ encryptions.

<<SM4-MatrixShe>> She's Master dissertation provided a SM4
16-round matrix distinguisher which can attack 18-round SM4, with data
complexity of $$2^127$$ chosen plaintexts and time complexity $$2^110.77$$
encryptions with memory storage of $$2^130$$.

<<SM4-MatrixWei>> Wei et al. applied differential analysis and algebraic attack
techniques on 20-round SM4 and discovered that the combined attack results on
20-round SM4 are superior than using pure differential cryptanalysis.

////
8) 矩阵攻击

2007年，Lu等人[21]给出了 SM4算法14轮的 矩阵攻击，需要的数据复杂度为212182个选择明 文，时间复杂度为2116‘66次算法加密.2008年，Toz 等人在文献[22]中进一步降低了文献[21]中给出 的矩阵攻击的数据和时间复杂度，最终的数据复 杂度为2m89个选择明文，时间复杂度为2l〇u9次 算法加密.同年，张蕾等人在文献<<SM4-DiffZhang1>.中给出了 SM4算法16轮的矩阵攻击，需要的数据复杂度为 2125个选择明文，时间复杂度为2116次算法加密. 2012年，薛萍在其硕士论文<<SM4-MatrixShe>>中给出了 SM4算 法16轮的矩形区分器，可以攻击到18轮，需要的 数据量为2127个选择明文，时间复杂度为2^77次 加密，存储量为21'此外，魏航等人结合差分 分析和代数攻击，对20轮SM4算法进行分析，发 现其效果比直接用差分分析攻击20轮SM4算法 的效果略好.
////

== Provable Security Against Differential And Linear Cryptanalysis

SM4 uses a novel structure differing from the general Feistel and SP
structures.

<<SM4-Random>> has proven that the SM4 non-balanced Feistel structure is
pseudo-random.

<<SM4-SLDC>> analyzes the SM4 non-balanced Feistel structure on its resistance
against differential and linear cryptanalysis techniques. Under SP type round
functions with branch number 5, it is proven that in a 27-round SM4 guarantees
at least 22 active S-boxes, therefore SM4 is secure against differential
attacks.

<<SM4-SLC>> analyzes resistance of SM4 against linear cryptanalysis.

////
9) 抗差分及线性密码分析的可证明安全性

SM4结构与之前的Feistel结构、SP结构等相比，是一种新型的结构.文献<<SM4-Random>>证明了 SM4 型的非平衡Feistel结构是伪随机的.针对SM4非平衡Feistel结构，有学者从结构上分析了其抗差 分和抗线性分析的能力.在分支数为5的SP型轮函数下，文献<<SM4-SLDC>>证明了 27轮SM4算法至少保 证22个活跃的S盒.因此，SM4算法是抗差分安全的.文献[33]则分析了SM4型算法抗线性分析的能力.
////

== Provable Security Against Related-Key Differential Cryptanalysis

Related-key differential cryptanalysis is related to the encryption algorithm
and key schedule. When performing a related-key attack, the attacker
simultaneously insert differences in both the key and the message.

In <<AutoDC>>, Sun et al. proposed an automated differential route search
method based on MILP (mixed-integer linear programming) that can be used to
assess the security bounds of a blockcipher under (related-key) differential
cryptanalysis.

// These are newer results than those in SM4-Details

<<SM4-RKDC>> describes the lower bounds of active S-boxes within SM4 as
follows:

[source]
----
-------------+---------------------------------------
Round        |  3 |  4 |  5 |  6 |  7 |  8 |  9 | 10
Single Key   |  0 |  1 |  2 |  2 |  5 |  6 |  7 |  8
Related Key  |  0 |  1 |  2 |  4 |  6 |  8 |  9 | 10
-------------+---------------------------------------
Round        | 11 | 12 | 13 | 14 | 15 | 16 | 17 | 18
Single Key   |  9 | 10 | 10 | 10 | 13 | 14 | 15 | 16
Related Key  | 11 | 13 | 14 | 14 | 16 | 18 | 19 | 20
-------------+---------------------------------------
Round        | 19 | 20 | 21 | 22 | 23 | 24 | 25 | 26
Single Key   | 18 | 18 | 19 | 20 | 22 | 23 | 23 | 24
Related Key  | 22 | -  | -  | -  | -  | -  | -  | -
-------------+---------------------------------------
("-" denotes unknown)
----

As the maximal probability of the SM4 S-box is $$2−6$$, when the minimum active
S-boxes reach 22 the differential characteristics will have probability
$$2^132$$, which is higher than enumeration ($$2^128$$).

This indicates that 19 rounds and 23 rounds under related key and single key
settings will provide a minimum of 22 active S-boxes and is able to resist
related-key differential attacks.

////
10) 抗相关密钥差分密码分析的可证明安全性

相关密钥差分分析与加密算法、密钥编排都有关.在进行相关密钥攻击时，攻击者同时在密钥和消息2个地方引入差分.孙思维等人提出的自动化差分路线搜索的方法是一种基于MILP (mixed-integer linear programming) 的方法，可以评估分组密码在（相关密钥）差分攻击下的安全界.

针对SM4,孙思维等人用整数规划方法(MILP) 给出了该算法抵抗相关密钥差分攻击的安全性分析结果.表3是相关密钥下的SM4各轮的最少活 跃S盒个数分布情况：

表3 SM4相关密钥自动化差分活跃S盒个数分布情况
轮数 3 4 5 6 7 8 9 10 11 12 13
S盒数 0 1 2 2 4 6 8 9 10 <=14

由于SM4的S盒差分概率是 2^-6，当最小活跃S盒的个数达到22时差分路径的概率为2^-132， 攻击难度高于穷举攻击.因此，可以用最小活跃S盒个数是否达到22作为衡量是否抵抗差分攻击 的一个标准.在相关密钥攻击下，当密钥的差分非零时，32轮的SM4算法的最小活跃S盒个数是 27个.因此32轮的SM4分组密码算法能够抵抗相关密钥差分攻击.
////


== Strongest Attacks Against SM4

////
// TODO: ENABLE

[cols="6*"]
|===

|Method
|Rounds
3+|Complexity
|Reference

|
|
|Time
|Data
|Memory
|

|Differential
|23
|$$2^126.7$$
|$$2^117$$
|$$2^120.7$$
|<<SM4-DiffSu>>

|Linear
|24
|$$2^122.6$$
|$$2^122.6$$
|$$2^85$$
|<<SM4-NLC>>

|Multi-dimensional Linear
|23
|$$2^122.7$$
|$$2^122.6$$
|$$2^120.6$$
|<<SM4-MLLiu2>>

|Impossible Differential
|17
|$$2^132$$
|$$2^117$$
|-
|<<SM4-IDCWang>>

|Zero-correlation Linear
|14
|$$2^120.7$$
|$$2^123.5$$
|$$2^73$$
|SM4-ZCLC

|Integral
|14
|$$2^96.5$$
|$$2^32$$
|-
|<<SM4-ICZhong>>

|Matrix
|18
|$$2^110.77$$
|$$2^127$$
|$$2^130$$
|<<SM4-MatrixShe>>

|===
////

As of the publication of this document, no open research results have provided
a method to successfully attack beyond 24 rounds of SM4.

The traditional view suggests that SM4 provides an extra safety margin
especially compared to other blockciphers adopted in <<ISO.IEC.18033-3>> that
already have full-round attacks, including MISTY1 <<MISTY1-IC>> <<MISTY1-270>>
and AES <<AES-CA>> <<AES-BC>> <<AES-RKC>>.

//从公开的研究结果可以看出，目前还没有一种分析方法能够在理论上攻破24轮的SM4算法.因此，从传统的分析方法来看，SM4算法具有较强的安全冗余度.尤其是对比MISTY1，AES等已有全轮攻击方案的分组密码算法，SM4算法具备一定的安全性优势.

