[#appendix-a]
= Appendix A: Example Calculations

//<!-- 附录A 运算示例 -->
== Examples From GB/T 32907-2016

=== Example 1

////
<!-- 本部分为 SM4 分组密码算法对一组明文进行加密的运算示例。
输入明文: 01 23 45 67 89 AB CD EF FE DC BA 98 76 54 32 10
输入密钥: 01 23 45 67 89 AB CD EF FE DC BA 98 76 54 32 10
轮密钥与每轮输出状态: -->
////

This is example 1 provided by <<GBT.32907-2016>> to demonstrate encryption of a
plaintext.

Plaintext:

[source]
----
01 23 45 67 89 AB CD EF FE DC BA 98 76 54 32 10
----

Encryption key:

[source]
----
01 23 45 67 89 AB CD EF FE DC BA 98 76 54 32 10
----

Status of the round key ($$rk_i$$) and round output ($$X_i$$) per round:

[source]
----
rk_0  = F12186F9   X_4  = 27FAD345
rk_1  = 41662B61   X_5  = A18B4CB2
rk_2  = 5A6AB19A   X_6  = 11C1E22A
rk_3  = 7BA92077   X_7  = CC13E2EE
rk_4  = 367360F4   X_8  = F87C5BD5
rk_5  = 776A0C61   X_9  = 33220757
rk_6  = B6BB89B3   X_10 = 77F4C297
rk_7  = 24763151   X_11 = 7A96F2EB
rk_8  = A520307C   X_12 = 27DAC07F
rk_9  = B7584DBD   X_13 = 42DD0F19
rk_10 = C30753ED   X_14 = B8A5DA02
rk_11 = 7EE55B57   X_15 = 907127FA
rk_12 = 6988608C   X_16 = 8B952B83
rk_13 = 30D895B7   X_17 = D42B7C59
rk_14 = 44BA14AF   X_18 = 2FFC5831
rk_15 = 104495A1   X_19 = F69E6888
rk_16 = D120B428   X_20 = AF2432C4
rk_17 = 73B55FA3   X_21 = ED1EC85E
rk_18 = CC874966   X_22 = 55A3BA22
rk_19 = 92244439   X_23 = 124B18AA
rk_20 = E89E641F   X_24 = 6AE7725F
rk_21 = 98CA015A   X_25 = F4CBA1F9
rk_22 = C7159060   X_26 = 1DCDFA10
rk_23 = 99E1FD2E   X_27 = 2FF60603
rk_24 = B79BD80C   X_28 = EFF24FDC
rk_25 = 1D2115B0   X_29 = 6FE46B75
rk_26 = 0E228AEB   X_30 = 893450AD
rk_27 = F1780C81   X_31 = 7B938F4C
rk_28 = 428D3654   X_32 = 536E4246
rk_29 = 62293496   X_33 = 86B3E94F
rk_30 = 01CF72E5   X_34 = D206965E
rk_31 = 9124A012   X_35 = 681EDF34
----

//<!-- 输出密文: 68 1E DF 34 D2 06 96 5E 86 B3 E9 4F 53 6E 42 46 -->

Ciphertext:

[source]
----
68 1E DF 34 D2 06 96 5E 86 B3 E9 4F 53 6E 42 46
----

=== Example 2

//<!-- A.2 示例 2 -->

////
<!-- 本部分为 SM4 分组密码算法使用固定的加密密钥，对一组明文反复加密1,000,000次的运算示例。 -->
////

This example is provided by <<GBT.32907-2016>> to demonstrate encryption of a
plaintext 1,000,000 times repeatedly, using a fixed encryption key.

//<!-- 输入明文: 01 23 45 67 89 AB CD EF FE DC BA 98 76 54 32 10 -->

Plaintext:

[source]
----
01 23 45 67 89 AB CD EF FE DC BA 98 76 54 32 10
----

//<!-- 输入密钥: 01 23 45 67 89 AB CD EF FE DC BA 98 76 54 32 10 -->

Encryption Key:
[source]
----
01 23 45 67 89 AB CD EF FE DC BA 98 76 54 32 10
----

//<!-- 输出密文: 59 52 98 C7 C6 FD 27 1F 04 02 F8 04 C3 3D 3F 66 -->

Ciphertext:
[source]
----
59 52 98 C7 C6 FD 27 1F 04 02 F8 04 C3 3D 3F 66
----

== Examples For Various Modes Of Operations

The following examples can be verified using open-source cryptographic
libraries including:

* the Botan cryptographic library <<BOTAN>> with SM4 support, and
* the OpenSSL Cryptography and SSL/TLS Toolkit <<OPENSSL>> with SM4 support


=== SM4-ECB Example

Plaintext:
[source]
----
AA AA AA AA BB BB BB BB CC CC CC CC DD DD DD DD 
EE EE EE EE FF FF FF FF AA AA AA AA BB BB BB BB
----

Encryption Key:
[source]
----
01 23 45 67 89 AB CD EF FE DC BA 98 76 54 32 10
----

Ciphertext:
[source]
----
5E C8 14 3D E5 09 CF F7 B5 17 9F 8F 47 4B 86 19
2F 1D 30 5A 7F B1 7D F9 85 F8 1C 84 82 19 23 04
00 2A 8A 4E FA 86 3C CA D0 24 AC 03 00 BB 40 D2
----


=== SM4-CBC Example

Plaintext:

[source]
----
AA AA AA AA BB BB BB BB CC CC CC CC DD DD DD DD 
EE EE EE EE FF FF FF FF AA AA AA AA BB BB BB BB
----

Encryption Key:
[source]
----
01 23 45 67 89 AB CD EF FE DC BA 98 76 54 32 10
----

IV:
[source]
----
00 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F 
----

Ciphertext:
[source]
----
78 EB B1 1C C4 0B 0A 48 31 2A AE B2 04 02 44 CB
4C B7 01 69 51 90 92 26 97 9B 0D 15 DC 6A 8F 6D
40 D8 41 32 E9 99 74 A4 A8 80 88 68 42 07 48 59
----

=== SM4-OFB Example

Plaintext:

[source]
----
AA AA AA AA BB BB BB BB CC CC CC CC DD DD DD DD 
EE EE EE EE FF FF FF FF AA AA AA AA BB BB BB BB
----

Encryption Key:
[source]
----
01 23 45 67 89 AB CD EF FE DC BA 98 76 54 32 10
----

IV:
[source]
----
00 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F 
----

Ciphertext:
[source]
----
AC 32 36 CB 86 1D D3 16 E6 41 3B 4E 3C 75 24 B7 
1D 01 AC A2 48 7C A5 82 CB F5 46 3E 66 98 53 9B 
----

=== SM4-CFB Example

Plaintext:
[source]
----
AA AA AA AA BB BB BB BB CC CC CC CC DD DD DD DD 
EE EE EE EE FF FF FF FF AA AA AA AA BB BB BB BB
----

Encryption Key:
[source]
----
01 23 45 67 89 AB CD EF FE DC BA 98 76 54 32 10
----

IV:
[source]
----
00 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F 
----

Ciphertext:
[source]
----
AC 32 36 CB 86 1D D3 16 E6 41 3B 4E 3C 75 24 B7
69 D4 C5 4E D4 33 B9 A0 34 60 09 BE B3 7B 2B 3F
----

=== SM4-CTR Example

Plaintext:
[source]
----
AA AA AA AA AA AA AA AA BB BB BB BB BB BB BB BB
CC CC CC CC CC CC CC CC DD DD DD DD DD DD DD DD
EE EE EE EE EE EE EE EE FF FF FF FF FF FF FF FF
EE EE EE EE EE EE EE EE AA AA AA AA AA AA AA AA
----

Encryption Key:
[source]
----
01 23 45 67 89 AB CD EF FE DC BA 98 76 54 32 10
----

IV:
[source]
----
00 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F 
----

Ciphertext:
[source]
----
AC 32 36 CB 97 0C C2 07 91 36 4C 39 5A 13 42 D1
A3 CB C1 87 8C 6F 30 CD 07 4C CE 38 5C DD 70 C7
F2 34 BC 0E 24 C1 19 80 FD 12 86 31 0C E3 7B 92
6E 02 FC D0 FA A0 BA F3 8B 29 33 85 1D 82 45 14
----

