
[bibliography]
= Normative References

//bibliography::norm[]
++++

<reference anchor='GBT.32907-2016' target='http://www.gb688.cn/bzgk/gb/newGbInfo?hcno=7803DE42D3BC5E80B0C3E5D8E873D56A'>
<!--http://www.sac.gov.cn/SACSearch/search?channelid=97779&templet=gjcxjg_detail.jsp&searchword=STANDARD_CODE=%27GB/T%2032907-2016%27 -->
  <front>
    <title>GB/T 32907-2016: Information security technology -- SM4 block cipher algorithm</title>
    <author>
      <organization>Standardization Administration of the People's Republic of China</organization>
      <address>
        <postal>
         <street>No. 9 Madian Donglu, Haidian District</street>
         <city>Beijing</city>
         <region>Beijing</region>
         <code>100088</code>
         <country>People's Republic of China</country>
        </postal>
        <phone>+86 (0)10 8226-2609</phone>
        <!--<email>contact@oscca.gov.cn</email>-->
        <uri>http://www.sac.gov.cn</uri>
      </address>
    </author>
    <date day='29' month='August' year='2016'/>
  </front>
</reference>

<reference anchor='ISO.IEC.18033-3' target='https://www.iso.org/standard/54531.html'>
  <front>
    <title>ISO/IEC 18033-3:2010 -- Encryption algorithms -- Part 3: Block ciphers</title>
    <author>
      <organization>International Organization for Standardization</organization>
      <address>
        <postal>
          <street>BIBC II</street>
          <street>Chemin de Blandonnet 8</street>
          <street>CP 401</street>
          <city>Vernier</city>
          <region>Geneva</region>
          <code>1214</code>
          <country>Switzerland</country>
        </postal>
        <phone>+41 22 749 01 11</phone>
        <email>central@iso.org</email>
        <uri>https://www.iso.org/</uri>
      </address>
    </author>
    <date day='1' month='December' year='2017'/>
  </front>
</reference>

<reference anchor='ISO.IEC.18033-3.AMD2' target='https://www.iso.org/standard/54531.html'>
  <front>
    <title>ISO/IEC WD1 18033-3/AMD2 -- Encryption algorithms -- Part 3: Block ciphers -- Amendment 2</title>
    <author>
      <organization>International Organization for Standardization</organization>
      <address>
        <postal>
          <street>BIBC II</street>
          <street>Chemin de Blandonnet 8</street>
          <street>CP 401</street>
          <city>Vernier</city>
          <region>Geneva</region>
          <code>1214</code>
          <country>Switzerland</country>
        </postal>
        <phone>+41 22 749 01 11</phone>
        <email>central@iso.org</email>
        <uri>https://www.iso.org/</uri>
      </address>
    </author>
    <date day='13' month='June' year='2017'/>
  </front>
</reference>

include::../reference.RFC.2119.xml[lines=3..-1]

++++


[bibliography]
= Informative References


//bibliography::info[]
++++

<reference anchor='SM4-Details' target='http://ris.sic.gov.cn/EN/Y2016/V2/I11/995'>
  <front>
    <title>Overview on SM4 Algorithm</title>
    <author initials="S." surname="Lu" fullname="Shuwang Lu">
      <organization>Data Assurance &amp; Communication Security Center, Chinese Academy of Science</organization>
      <address>
        <postal>
          <street></street>
          <city>Beijing</city>
          <code>100093</code>
          <country>People's Republic of China</country>
        </postal>
        <email>swlu@ustc.edu.cn</email>
      </address>
    </author>
    <author initials="B." surname="Su" fullname="Bozhan Su">
      <organization>State Key Laboratory of Cryptology</organization>
      <address>
        <postal>
          <street></street>
          <city>Beijing</city>
          <code>100878</code>
          <country>People's Republic of China</country>
        </postal>
        <email>subozhan@163.com</email>
      </address>
    </author>
    <author initials="P." surname="Peng" fullname="Peng Wang">
      <organization>Institute of InformationEngineering, Chinese Academy of Science</organization>
      <address>
        <postal>
          <street></street>
          <city>Beijing</city>
          <code>100093</code>
          <country>People's Republic of China</country>
        </postal>
        <email>wp@is.ac.cn</email>
      </address>
    </author>
    <author initials="Y." surname="Miao" fullname="Yingying Mao">
      <organization>Commercial Cryptography Testing Center</organization>
      <address>
        <postal>
          <street></street>
          <city>Beijing</city>
          <code>100036</code>
          <country>People's Republic of China</country>
        </postal>
        <email>maoyy2000@163.com</email>
      </address>
    </author>
    <author initials="L." surname="Huo" fullname="Lili Huo">
      <organization>Commercial Cryptography Testing Center</organization>
      <address>
        <postal>
          <street></street>
          <city>Beijing</city>
          <code>100093</code>
          <country>People's Republic of China</country>
        </postal>
        <email>lily.home.hao@163.com</email>
      </address>
    </author>
    <date day='25' month='October' year='2016'/>
  </front>
</reference>

<reference anchor='SM4-NLC' target='https://doi.org/10.1155/2017/1461520'>
  <front>
    <title>New Linear Cryptanalysis of Chinese Commercial Block Cipher Standard SM4</title>
    <author initials="Y." surname="Liu" fullname="Yu Liu">
      <organization>Key Laboratory of Cryptologic Technology and Information Security, Ministry of Education, Shandong University</organization>
      <address>
        <postal>
         <street>27 Shan Da Nan Lu, Licheng Qu</street>
         <city>Jinan</city>
         <region>Shandong</region>
         <code>250100</code>
         <country>People's Republic of China</country>
        </postal>
      </address>
    </author>
    <author initials="H." surname="Liang" fullname="Huicong Liang">
      <organization>Key Laboratory of Cryptologic Technology and Information Security, Ministry of Education, Shandong University</organization>
      <address>
        <postal>
         <street>27 Shan Da Nan Lu, Licheng Qu</street>
         <city>Jinan</city>
         <region>Shandong</region>
         <code>250100</code>
         <country>People's Republic of China</country>
        </postal>
      </address>
    </author>
    <author initials="W." surname="Wang" fullname="Wei Wang">
      <organization>Key Laboratory of Cryptologic Technology and Information Security, Ministry of Education, Shandong University</organization>
      <address>
        <postal>
         <street>27 Shan Da Nan Lu, Licheng Qu</street>
         <city>Jinan</city>
         <region>Shandong</region>
         <code>250100</code>
         <country>People's Republic of China</country>
        </postal>
      </address>
    </author>
    <author initials="M." surname="Wang" fullname="Meiqin Wang">
      <organization>Key Laboratory of Cryptologic Technology and Information Security, Ministry of Education, Shandong University</organization>
      <address>
        <postal>
         <street>27 Shan Da Nan Lu, Licheng Qu</street>
         <city>Jinan</city>
         <region>Shandong</region>
         <code>250100</code>
         <country>People's Republic of China</country>
        </postal>
        <email>mqwang@sdu.edu.cn</email>
      </address>
    </author>
    <date day='8' month='June' year='2017'/>
  </front>
</reference>

<reference anchor='SM4-RKDC' target='http://doi.org/10.1007/978-3-319-49151-6_5'>
  <front>
    <title>Security of SM4 Against (Related-Key) Differential Cryptanalysis</title>
    <author initials="J." surname="Zhang" fullname="Jian Zhang">
      <organization>Institute of Software, Chinese Academy of Sciences</organization>
      <address>
        <postal>
         <street>4 South Fourth Street, Zhong Guan Cun</street>
         <city>Beijing</city>
         <region>Beijing</region>
         <code>100190</code>
         <country>People's Republic of China</country>
        </postal>
        <email>zhangjian@tca.iscas.ac.cn</email>
      </address>
    </author>
    <author initials="W." surname="Wu" fullname="Wenling Wu">
      <organization>Institute of Software, Chinese Academy of Sciences</organization>
      <address>
        <postal>
         <street>4 South Fourth Street, Zhong Guan Cun</street>
         <city>Beijing</city>
         <region>Beijing</region>
         <code>100190</code>
         <country>People's Republic of China</country>
        </postal>
        <email>wwl@tca.iscas.ac.cn</email>
      </address>
    </author>
    <author initials="Y." surname="Zheng" fullname="Yafei Zheng">
      <organization>Institute of Software, Chinese Academy of Sciences</organization>
      <address>
        <postal>
         <street>4 South Fourth Street, Zhong Guan Cun</street>
         <city>Beijing</city>
         <region>Beijing</region>
         <code>100190</code>
         <country>People's Republic of China</country>
        </postal>
        <email>zhengyafei@tca.iscas.ac.cn</email>
      </address>
    </author>
    <date day='16' month='November' year='2016'/>
  </front>
</reference>

<reference anchor='GMT-0002-2012' target='http://www.oscca.gov.cn/Column/Column_32.htm'>
  <front>
    <title>GM/T 0002-2012: SM4 block cipher algorithm</title>
    <author>
      <organization>Organization of State Commercial Administration of China</organization>
      <address>
        <postal>
         <street>7 Dian Chang Lu, Fengtai Qu</street>
         <city>Beijing</city>
         <region>Beijing</region>
         <code>100036</code>
         <country>People's Republic of China</country>
        </postal>
        <phone>+86 (0)10 5970-3789</phone>
        <!--<email>contact@oscca.gov.cn</email>-->
        <uri>http://www.oscca.gov.cn</uri>
      </address>
    </author>
    <date day='21' month='March' year='2012'/>
  </front>
</reference>

<reference anchor='GMT-0006-2012' target='http://www.oscca.gov.cn/Column/Column_32.htm'>
  <front>
    <title>GM/T 0006-2012: Cryptographic Application Identifier Criterion Specification</title>
    <author>
      <organization>Organization of State Commercial Administration of China</organization>
      <address>
        <postal>
         <street>7 Dian Chang Lu, Fengtai Qu</street>
         <city>Beijing</city>
         <region>Beijing</region>
         <code>100036</code>
         <country>People's Republic of China</country>
        </postal>
        <phone>+86 (0)10 5970-3789</phone>
        <!--<email>contact@oscca.gov.cn</email>-->
        <uri>http://www.oscca.gov.cn</uri>
      </address>
    </author>
    <date day='21' month='March' year='2012'/>
  </front>
</reference>

<reference anchor='SM4' target='http://www.oscca.gov.cn/UpFile/200621016423197990.pdf'>
<!-- <reference anchor='SM4' target='http://info.dacas.cn/sharedimages/ARTICLES/SMAlgorithms/SM4.pdf'> -->
  <front>
    <title>SMS4 Cryptographic Algorithm For Wireless LAN Products</title>
    <author>
      <organization>Organization of State Commercial Administration of China</organization>
      <address>
        <postal>
         <street>7 Dian Chang Lu, Fengtai Qu</street>
         <city>Beijing</city>
         <region>Beijing</region>
         <code>100036</code>
         <country>People's Republic of China</country>
        </postal>
        <phone>+86 (0)10 5970-3789</phone>
        <!--<email>contact@oscca.gov.cn</email>-->
        <uri>http://www.oscca.gov.cn</uri>
      </address>
    </author>
    <date month='January' year='2006'/>
  </front>
</reference>


<reference anchor='GB.15629.11-2003' target='http://www.gb688.cn/bzgk/gb/newGbInfo?hcno=74B9DD11287E72408C19C4D3A360D1BD'>
  <front>
    <title>Information technology -- Telecommunications and information exchange between systems -- Local and metropolitan area networks -- Specific requirements -- Part 11: Wireless LAN Medium Access Control (MAC) and Physical Layer (PHY) Specifications</title>
    <author>
      <organization>Standardization Administration of the People's Republic of China</organization>
      <address>
        <postal>
         <street>No. 9 Madian Donglu, Haidian District</street>
         <city>Beijing</city>
         <region>Beijing</region>
         <code>100088</code>
         <country>People's Republic of China</country>
        </postal>
        <phone>+86 (0)10 8226-2609</phone>
        <!--<email>contact@oscca.gov.cn</email>-->
        <uri>http://www.sac.gov.cn</uri>
      </address>
    </author>
    <date day='12' month='May' year='2003'/>
  </front>
</reference>


<reference anchor='OSCCA' target='http://www.oscca.gov.cn'>
  <front>
    <title>Organization of State Commercial Administration of China</title>
    <author>
      <organization>Organization of State Commercial Administration of China</organization>
      <address>
        <postal>
         <street>7 Dian Chang Lu, Fengtai Qu</street>
         <city>Beijing</city>
         <region>Beijing</region>
         <code>100036</code>
         <country>People's Republic of China</country>
        </postal>
        <phone>+86 (0)10 5970-3789</phone>
        <!--<email>contact@oscca.gov.cn</email>-->
        <uri>http://www.oscca.gov.cn</uri>
      </address>
    </author>
    <date month='May' year='2017'/>
  </front>
</reference>

<reference anchor='SM4-Power' target='http://dx.doi.org/10.6028/NIST.FIPS.180-4'>
  <front>
    <!-- Journal on Communications Vol. 36 No 10. -->
    <title>Improved chosen-plaintext power analysis attack against SM4 at the round-output</title>
    <author initials="Z." surname="Du" fullname="Zhi-bo Du">
      <organization>College of Information Security Engineering, Chengdu University of Information Technology</organization>
      <address>
        <postal>
          <street>No. 24 Block 1, Xuefu Road</street>
          <city>Chengdu</city>
          <region>MD</region>
          <code>610225</code>
          <country>China</country>
        </postal>
        <uri>http://www.cuit.edu.cn/</uri>
      </address>
    </author>
    <author initials="Z." surname="Wu" fullname="Zhen Wu">
      <organization>College of Information Security Engineering, Chengdu University of Information Technology</organization>
      <address>
        <postal>
          <street>No. 24 Block 1, Xuefu Road</street>
          <city>Chengdu</city>
          <region>MD</region>
          <code>610225</code>
          <country>China</country>
        </postal>
        <uri>http://www.cuit.edu.cn/</uri>
      </address>
    </author>
    <author initials="M." surname="Wang" fullname="Min Wang">
      <organization>College of Information Security Engineering, Chengdu University of Information Technology</organization>
      <address>
        <postal>
          <street>No. 24 Block 1, Xuefu Road</street>
          <city>Chengdu</city>
          <region>MD</region>
          <code>610225</code>
          <country>China</country>
        </postal>
        <uri>http://www.cuit.edu.cn/</uri>
      </address>
    </author>
    <author initials="J." surname="Rao" fullname="Jin-tao Rao">
      <organization>College of Information Security Engineering, Chengdu University of Information Technology</organization>
      <address>
        <postal>
          <street>No. 24 Block 1, Xuefu Road</street>
          <city>Chengdu</city>
          <region>MD</region>
          <code>610225</code>
          <country>China</country>
        </postal>
        <uri>http://www.cuit.edu.cn/</uri>
      </address>
    </author>
    <date month='October' year='2015'/>
  </front>
</reference>

<reference anchor='NIST.FIPS.197' target='https://doi.org/10.6028/NIST.FIPS.197'>
  <front>
    <title>NIST FIPS 197: Advanced Encryption Standard (AES)</title>
    <author>
      <organization>National Institute of Standards and Technology</organization>
      <address>
        <postal>
          <street>100 Bureau Drive</street>
          <city>Gaithersburg</city>
          <region>MD</region>
          <code>20899-8900</code>
          <country>United States</country>
        </postal>
        <uri>http://www.nist.gov/</uri>
      </address>
    </author>
    <date month='November' year='2001'/>
  </front>
</reference>

<reference anchor='NIST.SP.800-38A' target='http://dx.doi.org/10.6028/NIST.SP.800-38A'>
  <front>
    <title>NIST Special Publication 800-38A: Recommendation for Block Cipher Modes of Operation -- Methods and Techniques</title>
    <author initials="M." surname="Dworkin" fullname="Morris Dworkin">
      <organization>National Institute of Standards and Technology</organization>
      <address>
        <postal>
          <street>100 Bureau Drive</street>
          <city>Gaithersburg</city>
          <region>MD</region>
          <code>20899-8930</code>
          <country>United States</country>
        </postal>
        <uri>http://www.nist.gov/</uri>
      </address>
    </author>
    <date month='December' year='2001'/>
  </front>
</reference>

<reference anchor='NIST.SP.800-38E' target='http://dx.doi.org/10.6028/NIST.SP.800-38E'>
  <front>
    <title>NIST Special Publication 800-38E: Recommendation for Block Cipher Modes of Operation: the XTS-AES Mode for Confidentiality on Storage Devices</title>
    <author initials="M." surname="Dworkin" fullname="Morris Dworkin">
      <organization>National Institute of Standards and Technology</organization>
      <address>
        <postal>
          <street>100 Bureau Drive</street>
          <city>Gaithersburg</city>
          <region>MD</region>
          <code>20899-8930</code>
          <country>United States</country>
        </postal>
        <uri>http://www.nist.gov/</uri>
      </address>
    </author>
    <date month='January' year='2010'/>
  </front>
</reference>

<reference anchor='IEEE.1619-2007' target='http://ieeexplore.ieee.org/document/4493450/'>
  <front>
    <title>IEEE P1619-2007: The XTS-AES Tweakable Block Cipher</title>
    <author>
      <organization>Institute of Electrical and Electronics Engineers, Inc</organization>
      <address>
        <postal>
          <street>Three Park Avenue</street>
          <city>New York</city>
          <region>NY</region>
          <code>10016-5997</code>
          <country>United States</country>
        </postal>
        <uri>http://www.ieee.org/</uri>
      </address>
    </author>
    <date day='18' month='April' year='2008'/>
  </front>
</reference>

<reference anchor='SM4-LDA' target='https://eprint.iacr.org/2008/281'>
  <front>
    <!-- Cryptology ePrint Archive, Report 2008/281 -->
    <title>Linear and Differential Cryptanalysis of Reduced SMS4 Block Cipher</title>
    <author initials="T." surname="Kim" fullname="Taehyun Kim">
      <organization>Center for Information Security Technologies (CIST), Korea University</organization>
      <address>
        <postal>
          <street>Room 615, International Center for Conversing Technology Building</street>
          <street>Anam Campus(Science), Korea University</street>
          <street>145 Anam-ro</street>
          <city>Seongbuk-gu</city>
          <region>Seoul</region>
          <code>02841</code>
          <country>Republic of Korea</country>
        </postal>
        <email>kimth714@cist.korea.ac.kr</email>
        <uri>http://gss.korea.edu/</uri>
      </address>
    </author>
    <author initials="J." surname="Kim" fullname="Jongsung Kim">
      <organization>Center for Information Security Technologies (CIST), Korea University</organization>
      <address>
        <postal>
          <street>Room 615, International Center for Conversing Technology Building</street>
          <street>Anam Campus(Science), Korea University</street>
          <street>145 Anam-ro</street>
          <city>Seongbuk-gu</city>
          <region>Seoul</region>
          <code>02841</code>
          <country>Republic of Korea</country>
        </postal>
        <email>joshep@cist.korea.ac.kr</email>
        <uri>http://gss.korea.edu/</uri>
      </address>
    </author>
    <author initials="S." surname="Kim" fullname="Seokhie Kim">
      <organization>Center for Information Security Technologies (CIST), Korea University</organization>
      <address>
        <postal>
          <street>Room 615, International Center for Conversing Technology Building</street>
          <street>Anam Campus(Science), Korea University</street>
          <street>145 Anam-ro</street>
          <city>Seongbuk-gu</city>
          <region>Seoul</region>
          <code>02841</code>
          <country>Republic of Korea</country>
        </postal>
        <email>hsh@cist.korea.ac.kr</email>
        <uri>http://gss.korea.edu/</uri>
      </address>
    </author>
    <author initials="J." surname="Sung" fullname="Jaechul Sung">
      <organization>Department of Mathematics, University of Seoul</organization>
      <address>
        <postal>
          <street>Department of Mathematical Sciences</street>
          <street>Seoul National University</street>
          <street>1 Gwan Ak-ro</street>
          <city>Gwanak-gu</city>
          <region>Seoul</region>
          <code>08826</code>
          <country>Republic of Korea</country>
        </postal>
        <email>jcsung@uos.ac.kr</email>
        <uri>http://uos.ac.kr/</uri>
      </address>
    </author>
    <date day='22' month='June' year='2008'/>
  </front>
</reference>

<reference anchor='SM4-Linear' target='https://doi.org/10.1007/s11390-014-1495-9'>
  <front>
    <!-- Journal of Computer Science and Technology, November 2014, Volume 29, Issue 6, pp 1123–1133 -->
    <title>Improved Linear Attacks on the Chinese Block Cipher Standard</title>
    <author initials="M." surname="Liu" fullname="Ming-Jie Liu">
      <organization>Beijing International Center for Mathematical Research, Peking University</organization>
      <address>
        <postal>
          <street>No. 5 Yiheyuan Road Haidian District</street>
          <city>Beijing</city>
          <code>100871</code>
          <country>People's Republic of China</country>
        </postal>
        <email>liumj9705@pku.edu.cn</email>
        <uri>http://www.bicmr.org</uri>
      </address>
    </author>
    <author initials="J." surname="Chen" fullname="Jia-Zhe Chen">
      <organization>China Information Technology Security Evaluation Center</organization>
      <address>
        <postal>
          <street>Building 1, No.8, Shangdi West Road, Haidian District</street>
          <city>Beijing</city>
          <code>100085</code>
          <country>People's Republic of China</country>
        </postal>
        <email>jiazhechen@gmail.com</email>
        <uri>http://www.itsec.gov.cn</uri>
      </address>
    </author>
    <date day='17' month='November' year='2014'/>
  </front>
</reference>

<reference anchor='SM4-FPGA' target='https://www.researchgate.net/publication/287081686_Improvements_of_SM4_algorithm_and_application_in_Ethernet_encryption_system_based_on_FPGA'>
  <front>
    <!-- article{article,
    author = {Cheng, H and Zhai, S and Fang, L and Ding, Q and Huang, C},
    year = {2014},
    month = {07},
    pages = {518-526},
    title = {Improvements of SM4 algorithm and application in Ethernet encryption system based on FPGA},
    volume = {5},
    booktitle = {Journal of Information Hiding and Multimedia Signal Processing}
    } -->
    <!-- Cryptology ePrint Archive, Report 2013/626 -->
    <title>Improvements of SM4 Algorithm and Application in Ethernet Encryption System Based on FPGA</title>
    <author initials="H." surname="Cheng" fullname="Hai Cheng">
      <organization>Key Laboratory of Electronic Engineering, University of Heilongjiang</organization>
      <address>
        <postal>
          <street>74 Xuefu Road</street>
          <city>Harbin</city>
          <region>Heilongjiang</region>
          <code>150080</code>
          <country>People's Republic of China</country>
        </postal>
        <email>chengh@hlju.edu.cn</email>
        <uri>httphttp://www.hlju.edu.cn/</uri>
      </address>
    </author>
    <author initials="S." surname="Zhai" fullname="Shuxia Zhai">
      <organization>Key Laboratory of Electronic Engineering, University of Heilongjiang</organization>
      <address>
        <postal>
          <street>74 Xuefu Road</street>
          <city>Harbin</city>
          <region>Heilongjiang</region>
          <code>150080</code>
          <country>People's Republic of China</country>
        </postal>
        <uri>httphttp://www.hlju.edu.cn/</uri>
      </address>
    </author>
    <author initials="L." surname="Fang" fullname="Lianzhong Fang">
      <organization>Key Laboratory of Electronic Engineering, University of Heilongjiang</organization>
      <address>
        <postal>
          <street>74 Xuefu Road</street>
          <city>Harbin</city>
          <region>Heilongjiang</region>
          <code>150080</code>
          <country>People's Republic of China</country>
        </postal>
        <email>chengh@hlju.edu.cn</email>
        <uri>httphttp://www.hlju.edu.cn/</uri>
      </address>
    </author>
    <author initials="Q." surname="Ding" fullname="Qun Ding">
      <organization>Key Laboratory of Electronic Engineering, University of Heilongjiang</organization>
      <address>
        <postal>
          <street>74 Xuefu Road</street>
          <city>Harbin</city>
          <region>Heilongjiang</region>
          <code>150080</code>
          <country>People's Republic of China</country>
        </postal>
        <email>qunding@aliyun.cn</email>
        <uri>httphttp://www.hlju.edu.cn/</uri>
      </address>
    </author>
    <author initials="C." surname="Huang" fullname="Chunguang Huang">
      <organization>Key Laboratory of Electronic Engineering, University of Heilongjiang</organization>
      <address>
        <postal>
          <street>74 Xuefu Road</street>
          <city>Harbin</city>
          <region>Heilongjiang</region>
          <code>150080</code>
          <country>People's Republic of China</country>
        </postal>
        <email>chenghdahuangr@163.com</email>
        <uri>http://www.hlju.edu.cn/</uri>
      </address>
    </author>
    <date day='01' month='July' year='2014'/>
  </front>
</reference>


<reference anchor='SM4-En' target='https://www.iacr.org/cryptodb/data/paper.php?pubkey=18006'>
  <front>
    <!-- https://www.iacr.org/cryptodb/data/paper.php?pubkey=18006 -->
    <title>SMS4 Encryption Algorithm for Wireless Networks</title>
    <author initials="W." surname="Diffie" fullname="Whitfield Diffie">
      <organization>Sun Microsystems</organization>
      <address>
        <postal>
          <street>4150 Network Circle</street>
          <city>Santa Clara</city>
          <region>CA</region>
          <code>95054</code>
          <country>United States of America</country>
        </postal>
        <email>whitfielddiffie@gmail.com</email>
        <uri>https://cisac.fsi.stanford.edu/</uri>
      </address>
    </author>
    <author initials="G." surname="Ledin" fullname="George Ledin">
      <organization>Sonoma State University</organization>
      <address>
        <postal>
          <street>Darwin 116, 1801 East Cotati Ave.</street>
          <city>Rohnert Park</city>
          <region>CA</region>
          <code>94928</code>
          <country>United States of America</country>
        </postal>
        <email>george.ledin@sonoma.edu</email>
        <uri>http://www.cs.sonoma.edu/</uri>
      </address>
    </author>
    <date day='15' month='May' year='2008'/>
  </front>
</reference>

<reference anchor='SM4-WhiteBox' target='http://dx.doi.org/10.1002/sec.1394'>
  <!-- @article {SEC:SEC1394,
  author = {Bai, Kunpeng and Wu, Chuankun},
  title = {A secure white-box SM4 implementation},
  journal = {Security and Communication Networks},
  volume = {9},
  number = {10},
  issn = {1939-0122},
  url = {http://dx.doi.org/10.1002/sec.1394},
  doi = {10.1002/sec.1394},
  pages = {996-1006},
  keywords = {white-box cryptography, SM4, secure implementation, lookup tables, obfuscation},
  year = {2016},
  note = {sec.1394},
  } -->
  <front>
    <title>A secure white-box SM4 implementation</title>
    <author initials="K." surname="Bai" fullname="Kunpeng Bai">
      <organization>State Key Laboratory of Information Security, Institute of Information Engineering, Chinese Academy of Sciences</organization>
      <address>
        <postal>
          <street>Institute of Software, Chinese Academy of Sciences</street>
          <street>No. 4 South Fourth Street</street>
          <city>Zhong Guan Cun</city>
          <region>Beijing</region>
          <code>100190</code>
          <country>People's Republic of China</country>
        </postal>
        <uri>http://www.is.cas.cn/</uri>
      </address>
    </author>
    <author initials="C." surname="Wu" fullname="Chuankun Wu">
      <organization>State Key Laboratory of Information Security, Institute of Information Engineering, Chinese Academy of Sciences</organization>
      <address>
        <postal>
          <street>Institute of Software, Chinese Academy of Sciences</street>
          <street>No. 4 South Fourth Street</street>
          <city>Zhong Guan Cun</city>
          <region>Beijing</region>
          <code>100190</code>
          <country>People's Republic of China</country>
        </postal>
        <email>ckwu@iie.ac.cn</email>
        <uri>http://www.is.cas.cn/</uri>
      </address>
    </author>
    <date day='15' month='May' year='2008'/>
  </front>
</reference>

<reference anchor='LSW-Bio' target='http://press.ustc.edu.cn/sites/default/files/fujian/field_fujian_multi/20120113/%E5%90%95%E8%BF%B0%E6%9C%9B%20%E5%AF%86%E7%A0%81%E4%B8%80%E6%A0%B7%E7%9A%84%E4%BA%BA%E7%94%9F.pdf'>
 <!-- 新华书目报　2010年11月25日 孙梦姝 -->
  <front>
    <title>Lv Shu Wang -- A life in cryptography</title>
    <author initials="M." surname="Sun" fullname="Mengshu Sun">
      <organization>Xinhua Catalog</organization>
    </author>
    <date day='25' month='November' year='2010'/>
  </front>
</reference>

<reference anchor='SideChannel' target='https://doi.org/10.1109/CIS.2015.102'>
  <!-- 2015 11th International Conference on Computational Intelligence and Security (CIS), Shenzhen, 2015, pp. 398-401. -->
  <front>
    <title>Software Hardware Co-design for Side-Channel Analysis Platform on Security Chips</title>
    <author initials="Q." surname="Lei" fullname="Qian Lei">
      <organization>Tsinghua National Laboratory for Information Science and Technology, Tsinghua University</organization>
      <address>
        <postal>
          <street>Tsinghua University</street>
          <city>Haidian</city>
          <region>Beijing</region>
          <code>100190</code>
          <country>People's Republic of China</country>
        </postal>
        <uri>http://www.sist.tsinghua.edu.cn/</uri>
      </address>
    </author>
    <author initials="L." surname="Wu" fullname="Liji Wu">
      <organization>Tsinghua National Laboratory for Information Science and Technology, Tsinghua University</organization>
      <address>
        <postal>
          <street>Tsinghua University</street>
          <city>Haidian</city>
          <region>Beijing</region>
          <code>100190</code>
          <country>People's Republic of China</country>
        </postal>
        <uri>http://www.sist.tsinghua.edu.cn/</uri>
      </address>
    </author>
    <author initials="S." surname="Zhang" fullname="Shaohui Zhang">
      <organization>Tsinghua National Laboratory for Information Science and Technology, Tsinghua University</organization>
      <address>
        <postal>
          <street>Tsinghua University</street>
          <city>Haidian</city>
          <region>Beijing</region>
          <code>100190</code>
          <country>People's Republic of China</country>
        </postal>
        <uri>http://www.sist.tsinghua.edu.cn/</uri>
      </address>
    </author>
    <author initials="X." surname="Zhang" fullname="Xiangmin Zhang">
      <organization>Tsinghua National Laboratory for Information Science and Technology, Tsinghua University</organization>
      <address>
        <postal>
          <street>Tsinghua University</street>
          <city>Haidian</city>
          <region>Beijing</region>
          <code>100190</code>
          <country>People's Republic of China</country>
        </postal>
        <uri>http://www.sist.tsinghua.edu.cn/</uri>
      </address>
    </author>
    <author initials="X." surname="Li" fullname="Xiangyu Li">
      <organization>Tsinghua National Laboratory for Information Science and Technology, Tsinghua University</organization>
      <address>
        <postal>
          <street>Tsinghua University</street>
          <city>Haidian</city>
          <region>Beijing</region>
          <code>100190</code>
          <country>People's Republic of China</country>
        </postal>
        <uri>http://www.sist.tsinghua.edu.cn/</uri>
      </address>
    </author>
    <author initials="L." surname="Pan" fullname="Liyang Pan">
      <organization>Tsinghua National Laboratory for Information Science and Technology, Tsinghua University</organization>
      <address>
        <postal>
          <street>Tsinghua University</street>
          <city>Haidian</city>
          <region>Beijing</region>
          <code>100190</code>
          <country>People's Republic of China</country>
        </postal>
        <uri>http://www.sist.tsinghua.edu.cn/</uri>
      </address>
    </author>
    <author initials="Z." surname="Dong" fullname="Zhimeng Dong">
      <organization>Tsinghua National Laboratory for Information Science and Technology, Tsinghua University</organization>
      <address>
        <postal>
          <street>Tsinghua University</street>
          <city>Haidian</city>
          <region>Beijing</region>
          <code>100190</code>
          <country>People's Republic of China</country>
        </postal>
        <uri>http://www.sist.tsinghua.edu.cn/</uri>
      </address>
    </author>
    <date day='1' month='December' year='2015'/>
  </front>
</reference>

<reference anchor='SM4-VLSI' target='https://doi.org/10.3233/JIFS-169011'>
<!-- Journal of Intelligent & Fuzzy Systems 31 (2016) 795–803
DOI:10.3233/JIFS-169011
IOS Press -->
  <front>
    <title>A VLSI implementation of an SM4 algorithm resistant to power analysis</title>
    <author initials="S." surname="Yu" fullname="Siyang Yu">
      <organization>College of Information Science and Engineering, Hunan University</organization>
      <address>
        <postal>
          <street>Lushan Road S, Yuelu District</street>
          <city>Changsha</city>
          <region>Hunan</region>
          <code>410082</code>
          <country>People's Republic of China</country>
        </postal>
        <email>nickysy@hnu.edu.cn</email>
        <uri>http://www.hnu.edu.cn/</uri>
      </address>
    </author>
    <author initials="K." surname="Li" fullname="Kenli Li">
      <organization>Department of Computer Science, New Platz, State University of New York</organization>
      <address>
        <postal>
          <street>SUNY New Paltz, 1 Hawk Drive</street>
          <city>New Paltz</city>
          <region>NY</region>
          <code>12561</code>
          <country>United States of America</country>
        </postal>
        <uri>http://www.hnu.edu.cn/</uri>
      </address>
    </author>
    <author initials="K." surname="Li" fullname="Keqin Li">
      <organization>College of Information Science and Engineering, Hunan University</organization>
      <address>
        <postal>
          <street>Lushan Road S, Yuelu District</street>
          <city>Changsha</city>
          <region>Hunan</region>
          <code>410082</code>
          <country>People's Republic of China</country>
        </postal>
        <uri>http://www.hnu.edu.cn/</uri>
      </address>
    </author>
    <author initials="Y." surname="Qin" fullname="Yunchuan Qin">
      <organization>College of Information Science and Engineering, Hunan University</organization>
      <address>
        <postal>
          <street>Lushan Road S, Yuelu District</street>
          <city>Changsha</city>
          <region>Hunan</region>
          <code>410082</code>
          <country>People's Republic of China</country>
        </postal>
        <uri>http://www.hnu.edu.cn/</uri>
      </address>
    </author>
    <author initials="Z." surname="Tong" fullname="Zhao Tong">
      <organization>College of Mathematics and Computer Science, Performance Computing and Stochastic Information Processing, (Ministry of Education of China), Hunan Normal University</organization>
      <address>
        <postal>
          <street>36 Lushan Rd., Yuelu District</street>
          <city>Changsha</city>
          <region>Hunan</region>
          <code>410081</code>
          <country>People's Republic of China</country>
        </postal>
        <uri>http://www.hunnu.edu.cn/</uri>
      </address>
    </author>
    <date day='22' month='July' year='2016'/>
  </front>
</reference>

<reference anchor='SM4-HiSpeed' target='http://dx.doi.org/10.14257/ijsia.2016.10.9.01'>
<!-- International Journal of Security and its Applications
Vol. 10, No. 9 (2016), pp.1-8
http://dx.doi.org/10.14257/ijsia.2016.10.9.01 -->
  <front>
    <title>High-speed Encryption &amp; Decryption System Based on SM4</title>
    <author initials="Q." surname="Lv" fullname="Qian Lv">
      <organization>Binzhou Polytechnic</organization>
      <address>
        <postal>
          <street>391 Huanghe Road</street>
          <city>Binzhou</city>
          <region>Shandong</region>
          <code>256600</code>
          <country>People's Republic of China</country>
        </postal>
        <email>ihappylucy@outlook.com</email>
        <uri>http://www.bzu.edu.cn/</uri>
      </address>
    </author>
    <author initials="L." surname="Li" fullname="Li Li">
      <organization>Binzhou Polytechnic</organization>
      <address>
        <postal>
          <street>391 Huanghe Road</street>
          <city>Binzhou</city>
          <region>Shandong</region>
          <code>256600</code>
          <country>People's Republic of China</country>
        </postal>
        <email>lili_thesky@163.com</email>
        <uri>http://www.bzu.edu.cn/</uri>
      </address>
    </author>
    <author initials="Y." surname="Cao" fullname="Yan-yan Cao">
      <organization>Binzhou Polytechnic</organization>
      <address>
        <postal>
          <street>391 Huanghe Road</street>
          <city>Binzhou</city>
          <region>Shandong</region>
          <code>256600</code>
          <country>People's Republic of China</country>
        </postal>
        <email>yaya_sd@163.com</email>
        <uri>http://www.bzu.edu.cn/</uri>
      </address>
    </author>
    <date day='22' month='July' year='2016'/>
  </front>
</reference>


<reference anchor='BC-EVAL' target='http://web.cs.ucdavis.edu/&tilde;rogaway/papers/modes.pdf'>
  <front>
    <title>Evaluation of Some Blockcipher Modes of Operation</title>
    <author initials="P." surname="Rogaway" fullname="Phillip Rogaway">
      <organization>University of California, Davis</organization>
      <address>
        <postal>
          <street>Dept. of Computer Science</street>
          <street>Kemper Hall of Engineering, #3009</street>
          <street>One Shields Avenue</street>
          <city>Davis</city>
          <region>California</region>
          <code>95616-8562</code>
          <country>United States of America</country>
        </postal>
        <phone>+1 530 752 7583</phone>
        <email>rogaway@cs.ucdavis.edu</email>
        <uri>http://www.cs.ucdavis.edu/&tilde;rogaway</uri>
      </address>
    </author>
    <date day='10' month='February' year='2011'/>
  </front>
</reference>

<reference anchor='BOTAN' target='https://botan.randombit.net'>
  <front>
    <title>Botan: Crypto and TLS for C++11</title>
    <author initials="J. E." surname="Lloyd" fullname="Jack E. Lloyd">
      <organization>Botan Project</organization>
      <address>
        <postal>
          <street></street>
          <country>United States of America</country>
        </postal>
        <email>jack@randombit.net</email>
        <uri>https://botan.randombit.net</uri>
      </address>
    </author>
    <date day='18' month='October' year='2017'/>
  </front>
</reference>

<reference anchor='OPENSSL' target='https://www.openssl.org'>
  <front>
    <title>OpenSSL: Cryptography and SSL/TLS Toolkit</title>
    <author>
      <organization>OpenSSL Software Foundation</organization>
      <address>
        <postal>
          <street>20-22 Wenlock Road</street>
          <city>London</city>
          <code>N1 7GU</code>
          <country>United Kingdom</country>
        </postal>
        <phone>+44 17 8550 8015</phone>
        <email>info@opensslfoundation.org</email>
        <uri>https://www.openssl.org</uri>
      </address>
    </author>
    <date day='18' month='October' year='2017'/>
  </front>
</reference>

<reference anchor='BC-Design' target='http://www.tup.tsinghua.edu.cn/booksCenter/book_03193701.html'>
  <front>
    <title>Block Cipher Design and Analysis (in Chinese)</title>
    <author initials="W." surname="Wu", fullname="Wenling Wu">
      <organization>Tsinghua University Press</organization>
    </author>
    <date day='1' month='October' year='2009'/>
  </front>
</reference>

<reference anchor='SM4-DiffZhang1' target='https://doi.org/10.1007/978-3-540-70500-0_16'>
  <front>
    <title>Cryptanalysis of Reduced-Round SMS4 Block Cipher</title>
    <author initials="L." surname="Zhang" fullname="Lei Zhang">
      <organization>State Key Laboratory of Information Security, Institute of Information Engineering, Chinese Academy of Sciences</organization>
      <address>
        <postal>
          <street>Institute of Software, Chinese Academy of Sciences</street>
          <street>No. 4 South Fourth Street</street>
          <city>Zhong Guan Cun</city>
          <region>Beijing</region>
          <code>100190</code>
          <country>People's Republic of China</country>
        </postal>
        <uri>http://www.is.cas.cn/</uri>
      </address>
    </author>
    <author initials="W." surname="Zhang" fullname="Wentao Zhang">
      <organization>State Key Laboratory of Information Security, Institute of Information Engineering, Chinese Academy of Sciences</organization>
      <address>
        <postal>
          <street>Institute of Software, Chinese Academy of Sciences</street>
          <street>No. 4 South Fourth Street</street>
          <city>Zhong Guan Cun</city>
          <region>Beijing</region>
          <code>100190</code>
          <country>People's Republic of China</country>
        </postal>
        <uri>http://www.is.cas.cn/</uri>
      </address>
    </author>
    <author initials="W." surname="Wu" fullname="Wenling Wu">
      <organization>State Key Laboratory of Information Security, Institute of Information Engineering, Chinese Academy of Sciences</organization>
      <address>
        <postal>
          <street>Institute of Software, Chinese Academy of Sciences</street>
          <street>No. 4 South Fourth Street</street>
          <city>Zhong Guan Cun</city>
          <region>Beijing</region>
          <code>100190</code>
          <country>People's Republic of China</country>
        </postal>
        <uri>http://www.is.cas.cn/</uri>
      </address>
    </author>
    <date day='7' month='July' year='2009'/>
  </front>
</reference>

<reference anchor='SM4-DiffZhang2' target='https://doi.org/10.1007/978-3-642-00843-6_28'>
  <front>
    <title>Some New Observations on the SMS4 Block Cipher in the Chinese WAPI Standard</title>
    <author initials="W." surname="Zhang" fullname="Wentao Zhang">
      <organization>State Key Laboratory of Information Security, Institute of Information Engineering, Chinese Academy of Sciences</organization>
      <address>
        <postal>
          <street>Institute of Software, Chinese Academy of Sciences</street>
          <street>No. 4 South Fourth Street</street>
          <city>Zhong Guan Cun</city>
          <region>Beijing</region>
          <code>100190</code>
          <country>People's Republic of China</country>
        </postal>
        <uri>http://www.is.cas.cn/</uri>
      </address>
    </author>
    <author initials="W." surname="Wu" fullname="Wenling Wu">
      <organization>State Key Laboratory of Information Security, Institute of Information Engineering, Chinese Academy of Sciences</organization>
      <address>
        <postal>
          <street>Institute of Software, Chinese Academy of Sciences</street>
          <street>No. 4 South Fourth Street</street>
          <city>Zhong Guan Cun</city>
          <region>Beijing</region>
          <code>100190</code>
          <country>People's Republic of China</country>
        </postal>
        <uri>http://www.is.cas.cn/</uri>
      </address>
    </author>
    <author initials="D." surname="Feng" fullname="Dengguo Feng">
      <organization>State Key Laboratory of Information Security, Institute of Information Engineering, Chinese Academy of Sciences</organization>
      <address>
        <postal>
          <street>Institute of Software, Chinese Academy of Sciences</street>
          <street>No. 4 South Fourth Street</street>
          <city>Zhong Guan Cun</city>
          <region>Beijing</region>
          <code>100190</code>
          <country>People's Republic of China</country>
        </postal>
        <uri>http://www.is.cas.cn/</uri>
      </address>
    </author>
    <author initials="B." surname="Su" fullname="Bozhan Su">
      <organization>State Key Laboratory of Information Security, Institute of Information Engineering, Chinese Academy of Sciences</organization>
      <address>
        <postal>
          <street>Institute of Software, Chinese Academy of Sciences</street>
          <street>No. 4 South Fourth Street</street>
          <city>Zhong Guan Cun</city>
          <region>Beijing</region>
          <code>100190</code>
          <country>People's Republic of China</country>
        </postal>
        <uri>http://www.is.cas.cn/</uri>
      </address>
    </author>
    <date day='7' month='July' year='2008'/>
  </front>
</reference>

<reference anchor='SM4-DiffSu' target='https://doi.org/10.1007/s11390-011-9420-y'>
  <front>
    <title>Security of the SMS4 Block Cipher Against Differential Cryptanalysis</title>
    <author initials="B." surname="Su" fullname="Bozhan Su">
      <organization>State Key Laboratory of Information Security, Institute of Information Engineering, Chinese Academy of Sciences</organization>
      <address>
        <postal>
          <street>Institute of Software, Chinese Academy of Sciences</street>
          <street>No. 4 South Fourth Street</street>
          <city>Zhong Guan Cun</city>
          <region>Beijing</region>
          <code>100190</code>
          <country>People's Republic of China</country>
        </postal>
        <email>subozhan@is.iscas.ac.cn</email>
        <uri>http://www.is.cas.cn/</uri>
      </address>
    </author>
    <author initials="W." surname="Wu" fullname="Wenling Wu">
      <organization>State Key Laboratory of Information Security, Institute of Information Engineering, Chinese Academy of Sciences</organization>
      <address>
        <postal>
          <street>Institute of Software, Chinese Academy of Sciences</street>
          <street>No. 4 South Fourth Street</street>
          <city>Zhong Guan Cun</city>
          <region>Beijing</region>
          <code>100190</code>
          <country>People's Republic of China</country>
        </postal>
        <uri>http://www.is.cas.cn/</uri>
      </address>
    </author>
    <author initials="W." surname="Zhang" fullname="Wentao Zhang">
      <organization>State Key Laboratory of Information Security, Institute of Information Engineering, Chinese Academy of Sciences</organization>
      <address>
        <postal>
          <street>Institute of Software, Chinese Academy of Sciences</street>
          <street>No. 4 South Fourth Street</street>
          <city>Zhong Guan Cun</city>
          <region>Beijing</region>
          <code>100190</code>
          <country>People's Republic of China</country>
        </postal>
        <uri>http://www.is.cas.cn/</uri>
      </address>
    </author>
    <date day='11' month='January' year='2011'/>
  </front>
</reference>

<reference anchor='SM4-Random' target='http://www.cnki.com.cn/Article/CJFDTOTAL-JSJX200907008.htm'>
  <!-- 张立廷，吴文玲.使用压缩函数的非平衡Feistel结构的伪随机性和超伪随机性[J].计算机学报，2009, 32(7): 1320-1330) -->
  <front>
    <title>Pseudorandomness and Super-pseudorandomness of a non-balanced Feistel Structure using compressed functions</title>
    <author initials="L." surname="Zhang" fullname="Liyen Zhang">
      <organization>State Key Laboratory of Information Security, Institute of Information Engineering, Chinese Academy of Sciences</organization>
      <address>
        <postal>
          <street>Institute of Software, Chinese Academy of Sciences</street>
          <street>No. 4 South Fourth Street</street>
          <city>Zhong Guan Cun</city>
          <region>Beijing</region>
          <code>100190</code>
          <country>People's Republic of China</country>
        </postal>
        <uri>http://www.is.cas.cn/</uri>
      </address>
    </author>
    <author initials="W." surname="Wu" fullname="Wenling Wu">
      <organization>State Key Laboratory of Information Security, Institute of Information Engineering, Chinese Academy of Sciences</organization>
      <address>
        <postal>
          <street>Institute of Software, Chinese Academy of Sciences</street>
          <street>No. 4 South Fourth Street</street>
          <city>Zhong Guan Cun</city>
          <region>Beijing</region>
          <code>100190</code>
          <country>People's Republic of China</country>
        </postal>
        <uri>http://www.is.cas.cn/</uri>
      </address>
    </author>
    <date day='1' month='January' year='2009'/>
  </front>
</reference>

<!-- SM4-LinearEtrog
https://doi.org/10.1007/978-3-642-04159-4_4
Etrog J., Robshaw M.J.B. (2009) The Cryptanalysis of Reduced-Round SMS4. In: Avanzi R.M., Keliher L., Sica F. (eds) Selected Areas in Cryptography. SAC 2008. Lecture Notes in Computer Science, vol 5381. Springer, Berlin, Heidelberg
Jonathan Etrog
Matt J. B. Robshaw
Orange Labs, Issy les Moulineaux, Cedex, France


SM4-LinearDong
[17] 董晓丽.分组密码AES和SM4的安全性分析[D].西安： 西安电子科技大学，2011
http://kns.cnki.net/KCMS/detail/detail.aspx?dbcode=CDFD&dbname=CDFD1214&filename=1013114416.nh
Xidian University
Security Analysis of the blockciphers AES and SM4
Xian, China

SM4-LinearLiu
https://doi.org/10.1007/s11390-014-1495-9
Improved Linear Attacks on the Chinese Block Cipher Standard
[18]    Liu Mingjie, Chen Jiazhe. Improved linear attacks on the Chinese block cipher standard [J]. Journal of Computer Science and Technology, 2014, 29(6)： 1123-1133
Ming-Jie Liu , liumj9705@pku.edu.cn
Beijing International Center for Mathematical Research, Peking University, Beijing, China
Jia-Zhe Chen
China Information Technology Security Evaluation Center, Beijing, China


SM4-MLLiu
http://citeseerx.ist.psu.edu/viewdoc/summary?doi=10.1.1.215.8314
Multiple Linear Cryptanalysis of Reduced-Round SMS4 Block Cipher
Liu Zhiqiang (ilu_zq@sjtu.edu.cn), Gu Dawu, Zhang Jing. Multiple linear cryptanalysis of reduced-round SM4 block cipher [J]. Chinese Journal of Electronics, 2010, 19(3)： 389-393
Department of Computer Science and Engineering, Shanghai Jiao Tong University, Shanghai 200240, P.R. China


SM4-MLCho
[20]    Cho J Y, Nyberg K. Improved linear cryptanalysis of SM4 block cipher [C] //Proc of the 9 th Int Workshop on Symmetric Key Encryption Workshop (SKEW). Vienna, Austria： SKEW, 2010
https://scholar.google.com.hk/scholar?cluster=13432379689578293076
Cho JY, Nyberg K. Improved linear cryptanalysis of SMS4 block cipher. In Symmetric Key Encryption Workshop 2011 Feb (pp. 1-14).

SM4-IDCLu
https://doi.org/10.1007/978-3-540-77048-0_24
Attacking Reduced-Round Versions of the SMS4 Block Cipher in the Chinese WAPI Standard
Lu Jiqiang
Information Security Group, Royal Holloway, University of London, Egham, Surrey TW20 0EXUK
[21]    Lu Jiqiang. Attacking reduced-round versions of the SM4 block cipher in the Chinese WAPI standard [C] //Proc of ICICS2007. Berlin： Springer, 2007： 306-318

SM4-IDCToz
https://doi.org/10.1007/978-3-540-88625-9_10
Analysis of Two Attacks on Reduced-Round Versions of the SMS4
Deniz Toz, Institute of Applied MathematicsMiddle East Technical UniversityAnkaraTurkey
Orr Dunkelman, Department of Electronical Engineering ESAT SDC-COSIC and Interdisciplinary Institute for BroadBand Technology (IBBT)Katholieke Universiteit LeuvenLeuven-HeverleeBelgium
[22]    Toz D, Dunkelman 〇.Analysis of two attacks on reduced-round versions of the SM4 [C] //Proc of ICICS 2008. Berlin： Springer, 2008： 141-156

SM4-IDCWang
http://ieeexplore.ieee.org/document/5629201/
Improved Impossible Differential Cryptanalysis on SMS4
Gaoli Wang
Sch. of Comput. Sci. & Technol., Donghua Univ., Shanghai, China
[23]    Wang Gaoli. Improved impossible differential cryptanalysis on SM4 [C] //Proc of Int Conf on Communications and Intelligence Information Security. Piscataway, NJ： IEEE, 2010： 105-108
13-14 Oct. 2010

SM4-ZCLC
http://www.jcr.cacrnet.org.cn:8080/mmxb/CN/abstract/abstract105.shtml
[24]
Multidimensional Zero-correlation Linear Cryptanalysis on SMS4 Algorithm
MA Meng 1, ZHAO Ya-Qun 1, LIU Qing-Cong 1, LIU Feng-Mei 2
1. State Key Laboratory of Mathematical Engineering and Advanced Computing, Information Engineering University, Zhengzhou, 450001, China
2. Science and Technology on Information Assurance Laboratory, Beijing 100072, China

SM4-ICLiu
https://doi.org/10.1007/978-3-540-73458-1_13
Analysis of the SMS4 Block Cipher
Fen Liu, State Key Laboratory of Information Security, Graduate School of Chinese Academy of Sciences, Beijing 100049China
Wen Ji, State Key Laboratory of Information Security, Graduate School of Chinese Academy of Sciences, Beijing 100049China
Lei Hu, State Key Laboratory of Information Security, Graduate School of Chinese Academy of Sciences, Beijing 100049China
Jintai Ding, Department of Mathematical Sciences, University of Cincinnati, Cincinnati, OH, 45221USA
Shuwang Lv, State Key Laboratory of Information Security, Graduate School of Chinese Academy of Sciences, Beijing 100049China
Andrei Pyshkin, Fachbereich Informatik, Technische Universität Darmstadt, 64289 DarmstadtGermany
Ralf-Philipp Weinmann, Fachbereich Informatik, Technische Universität Darmstadt, 64289 DarmstadtGermany
2007

SM4-ICZhong
http://www.cnki.com.cn/Article/CJFDTotal-XDKD200801019.htm
14-Round Square Attack on Blockcipher SMS4
Zhong Mingfu, Xidian University, Computer Network and Information Security Ministry of Education Key Laboratory
Hu Yupuo, Xidian University, Computer Network and Information Security Ministry of Education Key Laboratory
Chen Jie, Xidian University, Computer Network and Information Security Ministry of Education Key Laboratory
2008
[26] 钟名富，胡予濮，陈杰.分组密码算法SM4的14轮 Square攻击[J].西安电子科技大学学报：自然科学版， 2008, 35(1)： 105-109

SM4-AAJi
https://doi.org/10.1109/IAS.2009.171
Algebraic Attack to SMS4 and the Comparison with AES
Wen Ji
Beijing Electron. Sci. & Technol. Inst., Beijing, China
Lei Hu
State Key Lab. of Inf. Security, Grad. Univ. of Chinese Acad. of Sci., Beijing, China
Haiwen Ou
Beijing Electron. Sci. & Technol. Inst., Beijing, China
[27]    Ji Wen, Hu Lei, Ou Haiwen. Algebraic attack to SM4 and the comparison with AES [C] //Proc of the 5 th Int Conf on Information Assurance and Security. Piscataway, NJ ： IEEE, 2009： 662-665

SM4-AAEr
https://doi.org/10.1007/978-3-642-14423-3_6
Jeremy Erickson, The University of North Carolina at Chapel HillChapel Hill
Jintai Ding, The University of CincinnatiCincinnati
Chris Christensen, Northern Kentucky UniversityHighland Heights
Algebraic Cryptanalysis of SMS4: Gröbner Basis Attack and SAT Attack Compared
[28]    Erickson J, Ding J, Christensen C. Algebraic cryptanalysis of SM4： Groebner basis attack and SAT attack compared [C]//Proc of ICISC2009. Berlin： Springer, 2010： 73-86

SM4-MatrixShe
Matrix Attack On Blockcipher SMS4
http://cdmd.cnki.com.cn/Article/CDMD-10422-1012464969.htm
She Ping, Shandong University, Jinan, Shandong, China
Masters Dissertation
2012
薛萍.分组密码算法SMS4的矩形攻击[D].济南：山东大学，2012

SM4-MatrixWei
http://www.cnki.com.cn/Article/CJFDTotal-CDDD201202017.htm
Wei Hang, Chengdu University of Technology, School of Management Science
Cui Huili, Chengdu University of Technology, School of Management Science
Lv Xiaoxing, Chengdu University of Technology, School of Management Science
[30] 魏航，崔会丽，吕晓庆.SM4分组密码算法的差分-代数分析[J].成都大学学报：自然科学版，2012, 31(2): 158-160

SM4-DiffZhang3
22-Round SMS4 Differential Cryptanalysis
张美玲，刘景美，王新梅.22-轮SM4的差分分析[J].中 山大学学报：自然科学版，2010，49(2): 43-47
http://www.airitilibrary.com/Publication/alDetailedMesh?docid=05296579-201003-201004120040-201004120040-43-47
Zhang Meiling, National Key Lab of Integrated Service Networks, Xidian University, Xi’an 710071,China
Liu Jingmei, National Key Lab of Integrated Service Networks, Xidian University, Xi’an 710071,China
Wang Xinmei, National Key Lab of Integrated Service Networks, Xidian University, Xi’an 710071,China
2010

SM4-SLDC
Practically Secure against Differential Cryptanalysis for Block Cipher SMS4
http://www.ajetr.org/vol15/no1/n09.pdf
Zhang Meiling, School of communication and information engineering,  Xi’an University of Post and Telecommunications, Xi’an, China
Liu Yuanhua, School of communication and information engineering,  Xi’an University of Post and Telecommunications, Xi’an, China
Liu Jingmei, National Key Lab. of Integrated Service Networks,  Xidian University,  Xi’an ,China
Min Xiangshen, School of communication and information engineering,  Xi’an University of Post and Telecommunications, Xi’an, China
[32] Zhang Meiling，Liu Yuanhua, Liu Jingmei. Practically secure against differential cryptanalysis for block cipher SM4 [J]. American Journal of Engineering and Technology Research, 2011, 11(12)： 1923-1928

SM4-SLC
Practical security against linear cryptanalysis for SMS4-like ciphers with SP round function
https://doi.org/10.1007/s11432-011-4448-8
Zhang Bin, PO. Box 1936, Beijing 100193 China (dzjszhangbin@126.com)
Jin Chenhui, Electronic Technology Institute, Information Engineering University, Zhengzhou, China
[33]    Zhang Bin, Jin Chenhui. Practical security against linear cryptanalysis for SM4-like ciphers with SP round function [J]. Science China： Information Sciences, 2012，55(9): 2161-2170

AutoDC
Automatic Security Evaluation and (Related-key) Differential Characteristic Search: Application to SIMON, PRESENT, LBlock, DES(L) and Other Bit-Oriented Block Ciphers
https://doi.org/10.1007/978-3-662-45611-8_9
Siwei Sun, State Key Laboratory of Information Security, Institute of Information Engineering, Chinese Academy of Sciences, Beijing, China
Lei Hu, State Key Laboratory of Information Security, Institute of Information Engineering, Chinese Academy of Sciences, Beijing, China
Peng Wang, State Key Laboratory of Information Security, Institute of Information Engineering, Chinese Academy of Sciences, Beijing, China
Kexin Qiao, State Key Laboratory of Information Security, Institute of Information Engineering, Chinese Academy of Sciences, Beijing, China
Xiaoshuang Ma, State Key Laboratory of Information Security, Institute of Information Engineering, Chinese Academy of Sciences, Beijing, China
Ling Song, State Key Laboratory of Information Security, Institute of Information Engineering, Chinese Academy of Sciences, Beijing, China
[34]    Sun Siwei, Hu Lei, Wang Peng, et al. Automatic security evaluation and (related-key) differential characteristic search: Application to SIMON, PRESENT, LBlock, DES (L) and other bit-oriented block cipher [C] //Proc of ASIACRYPTC2014). Berlin： Springer, 2014： 158-178 -->

++++
